export default {
    branchId: null,
    addToCart: null,
    return_type: "stock_return",
    branches: [],
    products: [],
    branchProducts: [],
    filteredProducts: [],
    cartProducts: [],
    barcodeProduct: {},
    suppliers: [],
    customers: [],
    cashes: [],
    bankAccounts: [],
    banks: [],
    supplierBalance: 0,
    customerBalance: 0,
    oldPurchase: {},
    oldPurchaseReturn: {},
    oldSale: {},
    oldSaleReturn: {},
    oldDamage: {},
    oldProduction: {},
    oldProductTransfer: {},
    errors: [],
    isAdmin:false
};
